name: mybeautyadvisor
description: My Beauty Advisor App




version: 1.0.0+4

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev



environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_native_splash: 1.2.1
  flutter_svg: 0.22.0
  cupertino_icons: 1.0.0
  flutter_spinkit: 5.0.0
  shared_preferences: 2.0.5
  provider: 5.0.0
  http: 0.13.3
  intl_phone_field: 2.0.0
  flutter_rating_bar: 4.0.0
  flutter_share: 2.0.0
  image_picker: 0.8.0+4
  flutter_typeahead: 3.1.1
  animated_text_kit: 4.1.1
  toggle_switch: 1.2.0
  smartlook: 2.0.1
  ## Social Media Auth
  flutter_facebook_login: 3.0.0
  google_sign_in: 5.0.3


dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter


# Native Splash Screen
flutter_native_splash:
  # Normal Mode
  color: "#FFF8F8"
  image: assets/images/logo.png
  # Dark Mode
  color_dark: "#1a1a1a"
  image_dark: assets/images/logo_white.png
  android: true
  ios: true



# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # languages
    - i18n/en.json
    - i18n/fr.json
    - i18n/ar.json
    # Icons
    - assets/icons/
    - assets/icons/rating/
    # Images
    - assets/images/
    - assets/images/onboarding/
    - assets/images/onboarding/1/

  # Fonts used
  fonts:
    - family: BodoniModa
      fonts:
        - asset: assets/fonts/BodoniModa/BodoniModa-Regular.ttf
          weight: 600
        - asset: assets/fonts/BodoniModa/BodoniModa-Bold.ttf
          weight: 900

    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow/Barlow-Regular.ttf
          weight: 600
        - asset: assets/fonts/Barlow/Barlow-Bold.ttf
          weight: 900

